---
- name: Sanity checks
  ansible.builtin.include_tasks: sanity-checks.yml

- name: RHEL - Extra software
  ansible.builtin.include_tasks: extra-software/rhel-extra-software.yml
  when: ansible_facts["os_family"] == "RedHat"

- name: Debian - Extra software
  ansible.builtin.include_tasks: extra-software/debian-extra-software.yml
  when: ansible_facts["os_family"] == "Debian"

- name: User minecraft exist
  become: true
  ansible.builtin.user:
    name: "{{ minecraft_user_name }}"
    shell: "/bin/false"
    create_home: false
    state: present

- name: Install path exist
  become: true
  ansible.builtin.file:
    path: "{{ minecraft.path }}"
    state: directory
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "u=rwx,g=rwx,o=rx"

- name: Import Minecraft server stuff
  ansible.builtin.import_tasks: minecraft-server.yml
