---
- name: Sanity check - Eula
  assert:
    that: minecraft.eula is true
    success_msg: "You agreed the to the eula."
    fail_msg: |
      You have to agree the eula (more infos about the eula: https://aka.ms/MinecraftEULA).
      To agree the eula set 'eula: true'.

- block:
  - name: Check custom world dir
    delegate_to: localhost
    ansible.builtin.stat:
      path: "{{ minecraft.custom_world }}"
    register: check_custom_world_result
  
  - name: Sanity check - Custom world dir
    ansible.builtin.assert:
      that: check_custom_world_result.stat.exists
      success_msg: "Custom world dir found locally ({{ minecraft.custom_world }})."
      fail_msg: "Couldn't find custom world dir locally ({{ minecraft.custom_world }})."
  when: minecraft.custom_world != ''

- block:
  - name: Check local mods dir
    delegate_to: localhost
    ansible.builtin.stat:
      path: "{{ minecraft.fabric.local_mods }}"
    register: check_local_mods_result
  
  - name: Sanity check - Local mods
    ansible.builtin.assert:
      that: check_local_mods_result.stat.exists
      success_msg: "Local mods dir found ({{ minecraft.fabric.local_mods }})"
      fail_msg: "Local mods dir not found ({{ minecraft.fabric.local_mods }})"
  when: minecraft.fabric.local_mods != ''

