---
- name: Whitelist - Get UUID of name {{ name }}
  ansible.builtin.uri:
    url: "{{ mojang_api_username }}{{ name }}"
    method: "GET"
  ignore_errors: true
  register: http_response

- name: Check status code
  ansible.builtin.debug:
    msg: "Failed to find user {{ name }}."
  when: http_response.status != 200

- name: Convert UUID format
  ansible.builtin.set_fact:
    player:
      uuid: "{{ http_response.json.id[0:8] + '-' + http_response.json.id[8:12] + '-' + http_response.json.id[12:16] + '-' + http_response.json.id[16:20] + '-' + http_response.json.id[20:32] }}"
      name: "{{ http_response.json.name }}"

- name: Save name and UUID
  ansible.builtin.set_fact:
    full_whitelist: "{{ full_whitelist + [player] }}"
  when: http_response.status == 200

