---
- name: Add java to pkgs
  ansible.builtin.set_fact:
    pkgs: "{{ pkgs + ['openjdk-{{ instance_infos.javaVersion }}-jre-headless'] }}"

- name: Add acl to pkgs
  ansible.builtin.set_fact:
    pkgs: "{{ pkgs + ['acl'] }}"

- name: Install software
  become: true
  ansible.builtin.apt:
    name: "{{ pkgs }}"
