---
- name: Add java to pkgs
  ansible.builtin.set_fact:
    pkgs: "{{ pkgs + ['java-{{ instance_infos.javaVersion }}-openjdk-headless'] }}"

- name: Install software
  become: true
  ansible.builtin.dnf:
    name: "{{ pkgs }}"
